server:
    name: ei-ads-client
    port: 9000

logging:
    level:
      interfaceLogger: OFF
      ClusterConnectionManager: OFF
      PubSubConnectionPool: OFF
      SlaveConnectionPool: OFF
      org.redisson: OFF 
    file: log/ei-ads-client.log 

ads:  
  client: 
     thread: 4
     heartbeat: 1000
     ip:  192.168.1.70
     port: 9000
  defaultlifecycle: 60000
  memdb:
     lifecycle: 60000
  temp:
    dir: ./temp
  appDir: D:\GitHub\cim2ddl\code\bin_x64

buffer:
   channels:
       -
         name : commonChannel
         type : CACHE
   typePackage: com.znd.buffer.common.model
   #mapper加载路径
   mapperPackage: com.znd.buffer.common.mapper
   id:  0
   name: common
   alias: common
   createFlag: UPDATE
   
reliability:
  listenPort: 9002
  serverPort: 8950
  serverIp: 127.0.0.1
  serverThread: 4
  readyResponseTimeOut: 5
  cachedDir: ./pr-dir
  appDir: ${ads.appDir}     