server:
  name: ei-ads-client
  port: 9000

logging:
    level:
      interfaceLogger: OFF
      ClusterConnectionManager: OFF
      PubSubConnectionPool: OFF
      SlaveConnectionPool: OFF
      org.redisson: OFF 
    file: log/ei-ads-client.log 

    
#buffer配置  
buffer:
   id:  0
   name: common
   alias: 公共    
   createFlag: false
   
ads:
  client: 
     thread: 4
     heartbeat: 1000
     ip:  192.168.1.70
     port: ${server.port}