tcptest:
      serverIp: 192.168.1.33
      serverPort: 8950
      serverWorkers: 1
      serverTimeOut: 900000000
      hostIp: 192.168.1.70
      hostPort: 9002
logging:
  file: log/ei-ads-web.log
server:
  session-timeout : 3600
  name: ads
  port: 8080
model:
  cachedDir: ./model-cached-dir  

  
#数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://192.168.1.70:3306/ads?characterEncoding=utf-8&amp;serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver  
    
#mynatis配置
mybatis:
  type-aliases-package: com.znd.ei.ads.web.vo
  #mapper加载路径
  mapper-locations: classpath:mapper/*Mapper.xml
  #myatbis配置文件
  config-location: classpath:mybatis-conf.xml   
  
#buffer配置  
buffer:
   id:  0
   name: common
   alias: 公共
   tables:
      -  
        name:  AdsNode  
        columns:
            - 
              name: id
              alias: id
              type: integer
              indexable: true
            -
              name: name
              alias: 名称
              type: string
              indexable: true              
            -
              name: status
              alias: 状态
              type: integer
              indexable: false        