storage:
  location:com/znd/ei/memdb/domain
logging:
  file:log/ei-ads-console.log
server:
      name: ei-ads-console
      port: 8080

ads:
  defaultlifecycle: 600
  memdb:
     lifecycle: 6000
  aplSkip:
     - Test
     - Test1
  temp:
    dir: ./temp

  appDir: E:/ZNDProject/bin_x64

state-estimate:
  listenPort: 9001
  serverPort: 9002
  serverIp: 127.0.0.1
  serverThread: 4
  readyResponseTimeOut: 5
  cachedDir: D:/GitHub/cim2ddl/code/pr-dir
  
     
logging:
    level:
      interfaceLogger: OFF
      ClusterConnectionManager: OFF
      PubSubConnectionPool: OFF
      SlaveConnectionPool: OFF
io:
  netty:
    leakDetection:
      level: advanced
spring:
  redis:
    database: 0  
    host: 92.168.1.10
    port: 7000
    cluster:
      nodes: 
        - 192.168.3.70:7000
        - 192.168.3.70:7001
        - 192.168.3.70:7002
        - 192.168.3.70:7003
        - 192.168.3.70:7004
        - 192.168.3.70:7005
    password:  
    pool:
      max-active: 8  
      max-wait: -1  
      max-idle: 8  
      min-idle: 0  
    timeout: 0 