storage:
  location:com/znd/ei/memdb/domain

server:
      name: ei-ads-console
      port: 8080

ads:
  defaultlifecycle: 6000
  memdb:
     lifecycle: 6000
  aplSkip:
     - Test
     - Test1
  temp:
    dir: ./temp
  appDir: D:\GitHub\cim2ddl\code\bin_x64

state-estimate:
  listenPort: 9002
  serverPort: 8950
  serverIp: 127.0.0.1
  serverThread: 1
  readyResponseTimeOut: 5
  cachedDir: ./pr-dir
  appDir: ${ads.appDir}
     
logging:
    level:
      interfaceLogger: OFF
      ClusterConnectionManager: OFF
      PubSubConnectionPool: OFF
      SlaveConnectionPool: OFF
    file: log/ei-ads-console.log 
io:
  netty:
    leakDetection:
      level: advanced