storage:
  location:com/znd/ei/memdb/domain
logging:
  file:log/ei-ads-console.log
server:
      name: ei-ads-console
      port: 8080

ads:
  defaultlifecycle: 600
  memdb:
     lifecycle: 6000
  aplSkip:
     - Test
     - Test1
  temp:
    dir: ./temp

  appDir: E:/ZNDProject/SoftwareBeta/bin_x64

state-estimate:
  listenPort: 9003
  serverPort: 8950
  serverIp: 127.0.0.1
  serverThread: 4
  readyResponseTimeOut: 5
  cachedDir: D:/GitHub/cim2ddl/code/pr-dir
  
     
logging:
    level:
      interfaceLogger: OFF
      ClusterConnectionManager: OFF
      PubSubConnectionPool: OFF
      SlaveConnectionPool: OFF
io:
  netty:
    leakDetection:
      level: advanced