gencode:
   target: D:/GitHub/cim2ddl/code/ei-cim/ei-memdb-tool/code
   dbs: 
     - packageName: com.znd.ei.memdb.bpa.domain
       entryName: MemDB.Bpa
     - packageName: com.znd.ei.memdb.reliabilty.domain
       entryName: MemDB.PR
   enableEntityAnnotation: false
logging:
   file: log/myapp.log